package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"
	"fmt"

	"github.com/oscargh945/go-crud-graphql/domain"
	"github.com/oscargh945/go-crud-graphql/domain/entities"
	"github.com/oscargh945/go-crud-graphql/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input entities.CreateUserInput) (*entities.User, error) {
	if !domain.IsValidEmail(input.Email) {
		return nil, fmt.Errorf("Dirección de correo electrónico no válida")
	}
	if !domain.IsValidName(input.Name) {
		return nil, fmt.Errorf("El name agregado no es valido")
	}
	if !domain.IsValidPhone(input.Phone) {
		return nil, fmt.Errorf("El phone agregado no es valido")
	}
	domain.HashPassword(input.Password)
	user, err := r.UserUseCase.CreateUserUseCase(input)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*entities.User, error) {
	if admin, err := r.UserUseCase.Repository.GetCurrentUserFromCTX(ctx); err != nil {
		return nil, err
	} else if admin == nil {
		return nil, fmt.Errorf("Acceso denegado")
	}
	return r.UserUseCase.UpdateUserUseCase(id, input), nil
}

// SoftDeletedUser is the resolver for the softDeletedUser field.
func (r *mutationResolver) SoftDeletedUser(ctx context.Context, id string) (*model.DeleteUserResponse, error) {
	if admin, err := r.UserUseCase.Repository.GetCurrentUserFromCTX(ctx); err != nil {
		return nil, err
	} else if admin == nil {
		return nil, fmt.Errorf("Acceso denegado")
	}
	return r.UserUseCase.SoftDeleteUserUseCase(id), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginResponse, error) {
	return r.UserUseCase.LoginUseCase(input)
}

// Refresh is the resolver for the refresh field.
func (r *mutationResolver) Refresh(ctx context.Context, refreshToken string) (*model.LoginResponse, error) {
	return r.UserUseCase.RefreshUseCase(refreshToken)
}

// GetAllUsers is the resolver for the getAllUsers field.
func (r *queryResolver) GetAllUsers(ctx context.Context) ([]*entities.User, error) {
	if admin, err := r.UserUseCase.Repository.GetCurrentUserFromCTX(ctx); err != nil {
		return nil, err
	} else if admin == nil {
		return nil, fmt.Errorf("Acceso denegado")
	}
	if users, err := r.UserUseCase.GetAllUsersUseCase(); err != nil {
		return nil, err
	} else {
		return users, nil
	}
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*entities.User, error) {
	if admin, err := r.UserUseCase.Repository.GetCurrentUserFromCTX(ctx); err != nil {
		return nil, err
	} else if admin == nil {
		return nil, fmt.Errorf("Acceso denegado")
	}
	user, err := r.UserUseCase.GetUserUseCase(id)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// PaginationSearchUsers is the resolver for the paginationSearchUsers field.
func (r *queryResolver) PaginationSearchUsers(ctx context.Context, searchUser *string, page *int, pageSize *int) ([]*entities.User, error) {
	if page == nil {
		defaultPage := 1
		page = &defaultPage
	}

	if pageSize == nil {
		defaultPageSize := 3
		pageSize = &defaultPageSize
	}

	if searchUser == nil {
		defaultSeachUser := ""
		searchUser = &defaultSeachUser
	}

	if admin, err := r.UserUseCase.Repository.GetCurrentUserFromCTX(ctx); err != nil {
		return nil, err
	} else if admin == nil {
		return nil, fmt.Errorf("Acceso denegado")
	}
	users, err := r.UserUseCase.PaginationSearchUsersUseCase(searchUser, page, pageSize)
	if err != nil {
		return nil, err
	}
	if len(users) == 0 {
		return nil, fmt.Errorf("No se encontraron usuarios")
	}
	return users, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
