// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteUserResponse struct {
	DeleteUserID string `json:"deleteUserId"`
}

type UpdateUserInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	Phone *string `json:"phone,omitempty"`
}
